export const environment = {
  production: false,
  companyName: 'Dream Express BD',
  companyCode: 1,
  whatsappNumber: '1818545586',
  messengerUsername: 'favicon',
  apiUrl: 'https://api.chinatradexntour.com.bd/p',
  ImageApi: 'https://api.chinatradexntour.com.bd/uploads/',
  webUrl: 'https://dreamexpressbd.com',
  metaPixelId: '',
  metaCapiProxyUrl: '',
  siteDescription: 'dreamexpressbd - Your trusted online destination for quality products imported from China. Best prices, fast delivery, and reliable service across Bangladesh.',
  emptyImg: 'https://www.mykite.in/kb/NoImageFound.jpg.png',
  keywords: ['china products', 'import from china', 'wholesale products', 'china trade', 'online shopping Bangladesh', 'chinese products Bangladesh', 'dreamexpressbd', 'electronics', 'gadgets', 'affordable products'],
  socialLinks: {
    facebook: 'https://www.facebook.com/dreamexpressbd',
    instagram: 'https://www.instagram.com/dreamexpressbd',
    youtube: 'https://www.youtube.com/@dreamexpressbd',
  },
};
