export const environment = {
  production: false,
  companyName: 'Dream Express BD',
  companyCode: 1,
  whatsappNumber: '1327797921',
  messengerUsername: 'DreamExpressBD22',
  apiUrl: 'https://ecom.supersoftbd.com/p',
  ImageApi: 'https://ecom.supersoftbd.com/uploads/',
  webUrl: 'https://dreamexpressbd.com',
  googleClientId: '',
  metaPixelId: '',
  metaCapiProxyUrl: '',
  siteDescription: 'Dream Express BD - Your trusted online destination for quality products. Best prices, fast delivery, and reliable service across Bangladesh.',
  emptyImg: 'https://www.mykite.in/kb/NoImageFound.jpg.png',
  keywords: ['Fashion', 'dreamexpressbd', 'Dream Express BD'],
  socialLinks: {
    facebook: 'https://www.facebook.com/DreamExpressBD22',
    instagram: 'https://www.instagram.com/dreamexpressbd',
    youtube: 'https://www.youtube.com/@dreamexpressbd',
  },
};
