export const environment = {
    production: false,
    companyName: 'Dream Express BD',
    companyCode: 1,
    whatsappNumber: '1818545586',
    messengerUsername: 'md.kamrujjaman.822234',
    apiUrl: 'http://localhost:1005/p',
    ImageApi: 'http://localhost:1005/uploads/',
    webUrl: 'http://localhost:4200',
    siteDescription: 'Dream Express BD - Your trusted online shop for quality medical equipment, healthcare products, and diagnostic devices in Bangladesh. Fast delivery, secure payment, and great deals.',
    emptyImg: 'https://www.mykite.in/kb/NoImageFound.jpg.png',
    keywords: ['medical equipment', 'healthcare products', 'x-ray machine', 'medical printer', 'diagnostic equipment', 'radiology equipment', 'healthcare technology', 'medical devices Bangladesh', 'Dream Express BD', 'online medical shop Bangladesh'],
    googleClientId: '193969857306-f39301bin9ftfo7ruc1tmdn239v0j671.apps.googleusercontent.com',
    facebookAppId: '956878946919138',
    socialLinks: {
        facebook: 'https://www.facebook.com/dreamexpressbd',
        instagram: 'https://www.instagram.com/dreamexpressbd',
        youtube: 'https://www.youtube.com/@dreamexpressbd',
    },
};
